spring:
  application:
    name: job-matching-platform
  profiles:
    active: dev
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  jwt:
    secret: ${JWT_SECRET}
    expiration: 86400000

server:
  port: 8080