spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jobmatching_dev
    username: postgres
    password: 7654321
  jpa:
    show-sql: true

logging:
  level:
    com.seunome.jobmatchingplatform: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.security: DEBUG